sources=[#"res/nb-NO/nb-NO_NB88_07.sqlite",
         "res/nb-NO/nb-NO_DNB1930.sqlite",
        #  "res/en-US/en-US_NKJV.sqlite",
         ]
targets=[
    # "res/bg-BG/bg-BG_BG1940.sqlite",
    # "res/de-DE/de-DE_LUT2017.sqlite",
    #"res/en-US/en-US_NKJV.sqlite",
    # "res/es-ES/es-ES_RVR1960.sqlite",
    # "res/es-ES/es-ES_RV2020.sqlite",
    # "res/fr-FR/fr-FR_NEG79.sqlite",
    # "res/nl-NL/nl-NL_HSV.sqlite",
    # "res/nl-NL/nl-NL_NBG1951.sqlite",
    # "res/ru-RU/ru-RU_NRT.sqlite",
    # "res/ru-RU/ru-RU_SYNO.sqlite",
    # "res/sl-SI/sl-SI_SSP.sqlite",
    # "res/hr-HR/hr-HR_BKJ.sqlite",
    # "res/pl-PL/pl-PL_BW1975.sqlite",
    # "res/it-IT/it-IT_NR06.sqlite",
    # "res/ro-RO/ro-RO_VDC.sqlite",
    # "res/zh-CN/zh-CN_CUNPSS.sqlite",
    # "res/zh-HK/zh-HK_CUNPSS.sqlite",
    # "res/pt-BR/pt-BR_ARC.sqlite",
    # "res/tr-TR/tr-TR_TCL02.sqlite",
    "res/nb-NO/nb-NO_NB88_07.sqlite",
    # "res/kha-IN/kha-IN_BSI.sqlite",
]
